server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: 192.168.214.3:9092,192.168.214.3:9093,192.168.214.3:9094
    consumer:
      group-id: defaultConsumerGroup
    producer:
      retries: 1
    template:
      default-topic: encryptedFiles
      decode-topic: decodeFiles
  datasource:
    url: jdbc:mysql://localhost:3306/clouddesk?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Zy@123456
    druid:
      url: jdbc:mysql://localhost:3306/clouddesk?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Zy@123456
      ##-----------池大小设置-------------
      initial-size: 5
      max-active: 20
      min-idle: 5
      ##------------时间设置-------------
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      pool-prepared-statements: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #慢查询
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      ##------------监视器配置---------------
      #监视类型
      filters: stat,wall,stat,slf4j,default
      #web端监视
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #监控师徒配置
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        reset-enable: true
        login-username: admin
        login-password: 123456
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false
  ldap:
    urls: ldap://HQCQ-DC01.zy-ivd.com:389
    base: DC=zy-ivd,DC=com
    username: CN=rdpadmin,OU=ServiceAccounts,OU=Admins,OU=02-HQCQ,DC=zy-ivd,DC=com
    password: 8bnP6N3GyOK917OxKGuS
    template:
      ignore-partial-result-exception: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

logging:
  level:
    com.zybio.clouddesk.mapper: debug
  file:
    name: clouddesk.log
    path: C:/clouddesk/log

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

jwt:
  header: "Authorization"
  tokenPrefix: "Bearer"
  secret: abcdefg1234567
  expire: 7200

ad-manager:
  host: http://192.168.9.225:8030
  login: /RestAPI/APIAuthToken
  addGroup: /RestAPI/AddUsersToGroup
  loginName: itadapi
  password: scye$197tkuyx75839

webService:
  endpoint: http://localhost:8280/?wsdl
  loginName: vdi-api
  password: zFEHigD!DdBW#chN1NezC

file:
  path: c:\test
  tempPath: c:\test\temp

